server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/users?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asi
    username: root
    password: root
    pool:
      max-size: 100
      validation-query: SELECT 1


jwt:
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ=
  accessExpires:  7200000 #2시간 ms
  refreshExpires:  172800000 #2주 ms